name: portfolio
description: "A modern, responsive, and premium portfolio website for Anandhu Anil built using Flutter Web."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Typography
  google_fonts: ^6.2.1

  # Interactive animations and hover reveals
  flutter_animate: ^4.5.0

  # URL launching for social links and contact
  url_launcher: ^6.2.5


  # State management for layout offsets and navigation scrolling
  provider: ^6.1.2

  # Local storage for saving edits client-side
  shared_preferences: ^2.2.0

  # File picking for images and PDFs
  file_picker: ^8.0.0

  # Firebase Core and Firestore
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
